services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel11-app
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data11:/var/lib/mysql
    container_name: laravel11-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3312:3312"

  nginx:
    image: nginx:alpine
    container_name: laravel11-nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
volumes:
  db_data11:
